# Copyright (C) 2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/pantech/ef51/setup-makefiles.sh

#IM-A860L
PRODUCT_COPY_FILES += \
    vendor/pantech/ef51/proprietary/vendor/etc/firmware_ef51l/vidcfw.elf:system/vendor/etc/firmware_ef51l/vidcfw.elf \
    vendor/pantech/ef51/proprietary/vendor/etc/firmware_ef51l/vidc.mdt:system/vendor/etc/firmware_ef51l/vidc.mdt \
    vendor/pantech/ef51/proprietary/vendor/etc/firmware_ef51l/vidc.b00:system/vendor/etc/firmware_ef51l/vidc.b00 \
    vendor/pantech/ef51/proprietary/vendor/etc/firmware_ef51l/vidc.b01:system/vendor/etc/firmware_ef51l/vidc.b01 

#IM-A860S
PRODUCT_COPY_FILES += \
    vendor/pantech/ef51/proprietary/vendor/etc/firmware_ef51s/vidcfw.elf:system/vendor/etc/firmware_ef51s/vidcfw.elf \
    vendor/pantech/ef51/proprietary/vendor/etc/firmware_ef51s/vidc.mdt:system/vendor/etc/firmware_ef51s/vidc.mdt \
    vendor/pantech/ef51/proprietary/vendor/etc/firmware_ef51s/vidc.b00:system/vendor/etc/firmware_ef51s/vidc.b00 \
    vendor/pantech/ef51/proprietary/vendor/etc/firmware_ef51s/vidc.b01:system/vendor/etc/firmware_ef51s/vidc.b01 

#IM-A860K
PRODUCT_COPY_FILES += \
    vendor/pantech/ef51/proprietary/vendor/etc/firmware_ef51k/vidcfw.elf:system/vendor/etc/firmware_ef51k/vidcfw.elf \
    vendor/pantech/ef51/proprietary/vendor/etc/firmware_ef51k/vidc.mdt:system/vendor/etc/firmware_ef51k/vidc.mdt \
    vendor/pantech/ef51/proprietary/vendor/etc/firmware_ef51k/vidc.b00:system/vendor/etc/firmware_ef51k/vidc.b00 \
    vendor/pantech/ef51/proprietary/vendor/etc/firmware_ef51k/vidc.b01:system/vendor/etc/firmware_ef51k/vidc.b01 

PRODUCT_COPY_FILES += \
    vendor/pantech/ef51/proprietary/vendor/bin/sensors.qcom:system/vendor/bin/sensors.qcom \
    vendor/pantech/ef51/proprietary/vendor/lib/libmmcamera_faceproc.so:system/vendor/lib/libmmcamera_faceproc.so \
    vendor/pantech/ef51/proprietary/vendor/lib/libmmcamera_frameproc.so:system/vendor/lib/libmmcamera_frameproc.so \
    vendor/pantech/ef51/proprietary/vendor/lib/libmmcamera_hdr_lib.so:system/vendor/lib/libmmcamera_hdr_lib.so \
    vendor/pantech/ef51/proprietary/vendor/lib/libmmcamera_image_stab.so:system/vendor/lib/libmmcamera_image_stab.so \
    vendor/pantech/ef51/proprietary/vendor/lib/libmmcamera_imx091.so:system/vendor/lib/libmmcamera_imx091.so \
    vendor/pantech/ef51/proprietary/vendor/lib/libmmcamera_interface.so:system/vendor/lib/libmmcamera_interface.so \
    vendor/pantech/ef51/proprietary/vendor/lib/libmmcamera_interface2.so:system/vendor/lib/libmmcamera_interface2.so \
    vendor/pantech/ef51/proprietary/vendor/lib/libmmcamera_plugin.so:system/vendor/lib/libmmcamera_plugin.so \
    vendor/pantech/ef51/proprietary/vendor/lib/libmmcamera_statsproc31.so:system/vendor/lib/libmmcamera_statsproc31.so \
    vendor/pantech/ef51/proprietary/vendor/lib/libmmcamera_wavelet_lib.so:system/vendor/lib/libmmcamera_wavelet_lib.so \
    vendor/pantech/ef51/proprietary/vendor/lib/liboemcamera.so:system/vendor/lib/liboemcamera.so \
    vendor/pantech/ef51/proprietary/vendor/lib/libsensor1.so:system/vendor/lib/libsensor1.so \
    vendor/pantech/ef51/proprietary/vendor/lib/libsensor_reg.so:system/vendor/lib/libsensor_reg.so \
    vendor/pantech/ef51/proprietary/vendor/lib/libmmjpeg.so:system/vendor/lib/libmmjpeg.so \
    vendor/pantech/ef51/proprietary/vendor/lib/hw/camera.msm8960.so:system/vendor/lib/hw/camera.msm8960.so \
    vendor/pantech/ef51/proprietary/vendor/lib/hw/sensors.msm8960.so:system/vendor/lib/hw/sensors.ef51.so \
    vendor/pantech/ef51/proprietary/vendor/lib/hw/sensors_native_hal.so:system/vendor/lib/hw/sensors_native_hal.so \
    vendor/pantech/ef51/proprietary/vendor/lib/hw/sensors_qcom.so:system/vendor/lib/hw/sensors_qcom.so

PRODUCT_COPY_FILES += \
    vendor/pantech/ef51/proprietary/vendor/etc/firmware/cyttsp_8064_mtp.hex:system/vendor/firmware/cyttsp_8064_mtp.hex \
    vendor/pantech/ef51/proprietary/vendor/etc/firmware/cyttsp_8960_cdp.hex:system/vendor/firmware/cyttsp_8960_cdp.hex \
    vendor/pantech/ef51/proprietary/vendor/etc/firmware/leia_pfp_470.fw:system/vendor/firmware/leia_pfp_470.fw \
    vendor/pantech/ef51/proprietary/vendor/etc/firmware/leia_pm4_470.fw:system/vendor/firmware/leia_pm4_470.fw \
    vendor/pantech/ef51/proprietary/vendor/etc/firmware/vidc_1080p.fw:system/vendor/firmware/vidc_1080p.fw \
    vendor/pantech/ef51/proprietary/vendor/etc/firmware/vidc.b02:system/vendor/firmware/vidc.b02 \
    vendor/pantech/ef51/proprietary/vendor/etc/firmware/vidc.b03:system/vendor/firmware/vidc.b03 \
    vendor/pantech/ef51/proprietary/vendor/etc/firmware/libpn544_fw.so:system/vendor/firmware/libpn544_fw.so \
