# Generated by device/pantech/ef52/generate-prebuilts.py. Do not edit.
# SPDX-License-Identifier: Apache-2.0

PRODUCT_PACKAGES += \
    pantech_ef52_bin_sensors_qcom \
    pantech_ef52_lib_libmmcamera_faceproc_so \
    pantech_ef52_lib_libmmcamera_frameproc_so \
    pantech_ef52_lib_libmmcamera_hdr_lib_so \
    pantech_ef52_lib_libmmcamera_image_stab_so \
    pantech_ef52_lib_libmmcamera_interface_so \
    pantech_ef52_lib_libmmcamera_interface2_so \
    pantech_ef52_lib_libmmcamera_plugin_so \
    pantech_ef52_lib_libmmcamera_statsproc31_so \
    pantech_ef52_lib_libmmcamera_wavelet_lib_so \
    pantech_ef52_lib_liboemcamera_so \
    pantech_ef52_lib_libsensor1_so \
    pantech_ef52_lib_libsensor_reg_so \
    pantech_ef52_lib_libmmjpeg_so \
    pantech_ef52_lib_hw_camera_msm8960_vendor_so \
    pantech_ef52_lib_hw_sensors_native_hal_so \
    pantech_ef52_lib_hw_sensors_qcom_so

PRODUCT_COPY_FILES += \
    vendor/pantech/ef52/proprietary/vendor/etc/firmware_ef52l/vidcfw.elf:$(TARGET_COPY_OUT_VENDOR)/etc/firmware_ef52l/vidcfw.elf \
    vendor/pantech/ef52/proprietary/vendor/etc/firmware_ef52l/vidc.mdt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware_ef52l/vidc.mdt \
    vendor/pantech/ef52/proprietary/vendor/etc/firmware_ef52l/vidc.b00:$(TARGET_COPY_OUT_VENDOR)/etc/firmware_ef52l/vidc.b00 \
    vendor/pantech/ef52/proprietary/vendor/etc/firmware_ef52l/vidc.b01:$(TARGET_COPY_OUT_VENDOR)/etc/firmware_ef52l/vidc.b01 \
    vendor/pantech/ef52/proprietary/vendor/etc/firmware_ef52s/vidcfw.elf:$(TARGET_COPY_OUT_VENDOR)/etc/firmware_ef52s/vidcfw.elf \
    vendor/pantech/ef52/proprietary/vendor/etc/firmware_ef52s/vidc.mdt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware_ef52s/vidc.mdt \
    vendor/pantech/ef52/proprietary/vendor/etc/firmware_ef52s/vidc.b00:$(TARGET_COPY_OUT_VENDOR)/etc/firmware_ef52s/vidc.b00 \
    vendor/pantech/ef52/proprietary/vendor/etc/firmware_ef52s/vidc.b01:$(TARGET_COPY_OUT_VENDOR)/etc/firmware_ef52s/vidc.b01 \
    vendor/pantech/ef52/proprietary/vendor/etc/firmware_ef52k/vidcfw.elf:$(TARGET_COPY_OUT_VENDOR)/etc/firmware_ef52k/vidcfw.elf \
    vendor/pantech/ef52/proprietary/vendor/etc/firmware_ef52k/vidc.mdt:$(TARGET_COPY_OUT_VENDOR)/etc/firmware_ef52k/vidc.mdt \
    vendor/pantech/ef52/proprietary/vendor/etc/firmware_ef52k/vidc.b00:$(TARGET_COPY_OUT_VENDOR)/etc/firmware_ef52k/vidc.b00 \
    vendor/pantech/ef52/proprietary/vendor/etc/firmware_ef52k/vidc.b01:$(TARGET_COPY_OUT_VENDOR)/etc/firmware_ef52k/vidc.b01 \
    vendor/pantech/ef52/proprietary/vendor/etc/firmware/cyttsp_8064_mtp.hex:$(TARGET_COPY_OUT_VENDOR)/firmware/cyttsp_8064_mtp.hex \
    vendor/pantech/ef52/proprietary/vendor/etc/firmware/cyttsp_8960_cdp.hex:$(TARGET_COPY_OUT_VENDOR)/firmware/cyttsp_8960_cdp.hex \
    vendor/pantech/ef52/proprietary/vendor/etc/firmware/leia_pfp_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pfp_470.fw \
    vendor/pantech/ef52/proprietary/vendor/etc/firmware/leia_pm4_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pm4_470.fw \
    vendor/pantech/ef52/proprietary/vendor/etc/firmware/vidc_1080p.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/vidc_1080p.fw \
    vendor/pantech/ef52/proprietary/vendor/etc/firmware/vidc.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/vidc.b02 \
    vendor/pantech/ef52/proprietary/vendor/etc/firmware/vidc.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/vidc.b03 \
    vendor/pantech/ef52/proprietary/vendor/etc/firmware/libpn544_fw.so:$(TARGET_COPY_OUT_VENDOR)/firmware/libpn544_fw.so
